#!/usr/bin/env bash

which -s gcloud
if [[ $? != 0 ]]; then
  echo 'Setup requires `gcloud` available on the shell PATH.'
  exit 128
fi
which -s kubectl
if [[ $? != 0 ]]; then
  echo 'Setup requires `kubectl` available on the shell PATH.'
  exit 127
fi


GCLOUD_PROJECT=$1
GCLOUD_ACCOUNT=$2
DEPLOYMENT_NAME=$3
DOMAIN=$4
DOMAIN_EMAIL=$5
PRODUCTION_MODE=$6

if [[ -z $GCLOUD_PROJECT ]]; then
  echo "Please specify a Gcloud project name as arg 1."
  exit 1
fi

if [[ -z $GCLOUD_ACCOUNT ]]; then
  echo "Please specify a Gcloud account name as arg 2."
  exit 2
fi

if [[ -z $DEPLOYMENT_NAME ]]; then
  echo "Please specify a deployment name as arg 3."
  exit 3
fi

if [[ -z $DOMAIN ]]; then
  echo "Please specify a domain name as arg 4."
  exit 4
fi

if [[ -z $DOMAIN_EMAIL ]]; then
  echo "Please specify a domain name registered email address as arg 5."
  exit 5
fi

if [[ -z $PRODUCTION_MODE ]]; then
  STAGING_MODE="true"
else
  STAGING_MODE=""
fi

wdir=/tmp/$DEPLOYMENT_NAME
mkdir -p $wdir
cat init.yml.tmpl | sed s/DEPLOYMENT_NAME/$DEPLOYMENT_NAME/g | sed s/DOMAIN_EMAIL/$DOMAIN_EMAIL/g | sed s/DOMAINS_VALUE/$DOMAIN/g > $wdir/init.yml
cat securing.yml.tmpl | sed s/DEPLOYMENT_NAME/$DEPLOYMENT_NAME/g | sed s/DOMAIN_EMAIL/$DOMAIN_EMAIL/g | sed s/DOMAINS_VALUE/$DOMAIN/g | sed s/STAGING_MODE/$STAGING_MODE/g > $wdir/securing.yml
cat secured.yml.tmpl | sed s/DEPLOYMENT_NAME/$DEPLOYMENT_NAME/g | sed s/DOMAIN_EMAIL/$DOMAIN_EMAIL/g | sed s/DOMAINS_VALUE/$DOMAIN/g > $wdir/secured.yml
cat delete.yml.tmpl | sed s/DEPLOYMENT_NAME/$DEPLOYMENT_NAME/g | sed s/DOMAIN_EMAIL/$DOMAIN_EMAIL/g | sed s/DOMAINS_VALUE/$DOMAIN/g > $wdir/delete_$DEPLOYMENT_NAME.yml

function guard_cmd {
  set -e
  $1
  set +e
}

#
# Login to the Glcoud environment
#
guard_cmd "gcloud auth login $GCLOUD_ACCOUNT --quiet --brief --activate --project $GCLOUD_PROJECT"

#
# Build the basic infrastructure.
#
guard_cmd "kubectl apply -f $wdir/init.yml"

#
# Wait for the basic infrastructure to be online.
#
#   * Wait for an ingress IP address.
#   * Wait for the domain name to answer on that IP address.
#
ip_address=
function attempt_get_ip {
  ip_address=`kubectl get ingress -o=jsonpath='{.status.loadBalancer.ingress[*].ip}' $DEPLOYMENT_NAME-ingress`
}
echo -n "Waiting for IP address"
while [ -z $ip_address ]
do
  echo -n "."
  attempt_get_ip
  sleep 1
done
echo

domain_test=42
function test_domain {
  curl --silent --fail $DOMAIN
  domain_test=$?
}
echo -n "Waiting for $DOMAIN to get to $ip_address (please register as an A record, nothing to do if already set)"
while [ $domain_test != 0 ]
do
  echo -n "."
  test_domain
  sleep 1
done
echo

guard_cmd "kubectl apply -f $wdir/securing.yml"
guard_cmd "kubectl apply -f $wdir/secured.yml"

echo Setup complete:
echo -e "\tCluster IP address (ingress): $ip_address"
echo -e "\tCluster DNS: $DOMAIN"
echo -e "\tDeletion command: kubectl delete -f $wdir/delete_$DEPLOYMENT_NAME.yml"
echo -e "\tWarning: Please save the deletion script if you want to use it later ($wdir may get erased)."
